language: rust
rust:
  - nightly
script:
  - cargo build
  - cargo test
  - cargo doc
services:
  - postgresql
before_script:
  - psql -c 'create database hstore_test;' -U postgres
env:
  - DATABASE_URL=postgres://postgres@localhost/hstore_test
