[package]
name = "diesel_pg_hstore"
version = "0.1.0"
authors = ["Lori Holden <noreply@loriholden.com>"]

[dependencies]
diesel = { version = "~1.0.0-beta1", features = ["postgres"] }
byteorder = "~1.2"
fallible-iterator = "~0.1"

[dev-dependencies]
dotenv = "~0.10"
